### ISSUE TITLE
Feature: Add staff functionality

### ISSUE THREAD

**Issue by royalroot** [adamspd/django-appointment#1]
Hi,
first of all thanks for creating this amazing plugin.
I did not used it yet but as I read the docs I think this has much potential.
I want to do a very similar thing accept that I need support for a staff feature. I am thinking about availability of staff members on some days, holidays, services only some staffys will do etc.
Is this something you will implement as well?
greetings,
Nico

**Comment by adamspd** [comment]
Hi @royalroot, thank you very much for taking an interest into the plugin. I did not fully understand the functionality you described that you wanted, can you please provide a use case for it ? To be honest, I didn't think of adding staff functionality, but it's possible to add it (after I understand how you want it to work) and extend the use case of the plugin.

**Comment by royalroot** [comment]
Hi @adamspd ,
thank you for your quick reply. I'm thinking about a functionality where multiple worker /staff people offer different or the same services. I'm thinking about the functionality like in bookly pro, a wordpress plugin.
There it is described as follows:
"Unlimited number of Staff Members with individual working schedules, prices, and ability to manage their profiles and online booking calendar;"
This means that each staff member can set his or her working times, holidays and even which services they offer.
Do you understand? I try to install your plugin in the next days and investigate if i can add this. But if you have a suggestion it would be very helpful.
Thank you

**Comment by adamspd** [comment]
Hi @royalroot, yes, this was planned. I didn't understand what you wanted at the beginning.
I was thinking of adding the possibility to have a list of staff member that client would choose from and get their schedule to book them. As you said, the staff member would have the possibility to set their own schedule, etc...

**Comment by royalroot** [comment]
Hi @adamspd,
sounds great. This is all that I need.
Do you know when this feature will be available?
Feel free to close this issue if you don't need it as "reminder".
Thanks a lot,
Nico

**Comment by adamspd** [comment]
Hi @royalroot, so sorry for the late response. I'm currently improving the actual version of the package. I think a release candidate for this feature will be available around next week.

**Comment by royalroot** [comment]
Hi @adamspd,
no worries. This is great news thank you.
I must confess that i haven't found the time to test your plugin in detail yet either. But the function will help me and my application a lot. Thank you for your effort.
Feel free to let me know when you are done then I will test it once.
I promise :)
