### ISSUE TITLE
no photos/videos in readme

### ISSUE THREAD

**Issue by wiktorcie** [adamspd/django-appointment#17]
Please consider adding some.

**Comment by adamspd** [comment]
What do you mean ? 

Photos/Videos of how it works or how to configure it ?

**Comment by wiktorcie** [comment]
you can have photos and videos in readmes in github.  check one of my repos -> https://github.com/wiktorcie/onlybtcfans
I'm on fedora, so I usually record/print screen using built in tools and paste/drag them into the readme file I'm editing. 
Super easy, no need to configure anything, it's just drag and drop.  

It is very beneficial as someone can quickly gauge if he wants to use the project without going through the hassle of setting it up locally.  As this project has bunch of frontend components I think that would be useful.

**Comment by adamspd** [comment]
Thanks @wiktorcie, not a bad idea actually. I'll see what I can do.

**Comment by wiktorcie** [comment]
I recommend obs studio if you are not aware of it.

pt., 24 lis 2023, 19:22 użytkownik Adams Pierre David <
***@***.***> napisał:
