### ISSUE TITLE
Be able to disable email verification when booking an appointment

### ISSUE THREAD

**Issue by SDeVuyst** [adamspd/django-appointment#173]
## Feature Description
When booking an appointment, the client is required to enter their email and confirm with an auth code. In some use cases this is unnecessary.

## The Ideal Solution
An option so the email verification code step can be skipped, and the client goes straight to the thank-you/payment page. Maybe even an option that does not require the client to enter their email at all.

## Priority
How important is this feature to you?
- [ ] Critical
- [x] High
- [x] Medium
- [ ] Low

**Comment by adamspd** [comment]
Hello @SDeVuyst,

Could you clarify what you meant by "in some use cases, this is unnecessary"? I'm interested in understanding the specific scenarios you're referring to, purely for my own learning and knowledge.

Also, would you be available to assist with or contribute to a pull request incorporating the changes you mentioned? If that's not possible for you at the moment, I'll take the initiative to implement them myself in a later release.

Thank you for your input and assistance.

**Comment by SDeVuyst** [comment]
Hi, thanks for your quick response. 

My use case is a local pediatrician. They would prefer that their patients don't even need to input any email adress, so an email with an auth code is a definite no. I know this is vulnerable for spamming, but they are ok with this.

I will take a look to implement this myself, but no promises as I am pretty busy for the moment.

Thanks

**Comment by adamspd** [comment]
Before you begin working on the implementation, could you inform me? I aim to avoid overlapping efforts. I'm currently addressing some other issues, but plan to focus on this next. It would be great to exchange ideas if you've started coding by then.

**Comment by SDeVuyst** [comment]
I can actually start working on this the 4th of april already. I don't think this will be too much of a hassle to implement (watch this backfire on me...)  How do you suggest we move forward? - and are there any guidelines you want me to follow? I think I would rather implement a system so you will be able to book without an email adress, rather than disabling the verification. This fits my use case more

**Comment by adamspd** [comment]
Sorry it took me so long to reply. Well, you can start the pull request, and I can revise from there. But I'm not sure that it's easy, I mean the logic in the code, yes, but there may be a few functions that need tweaking. To start with, I'd say you need to add a variable to settings.py that will determine whether you want email to be mandatory or not, and based on that, remove the email field from the forms and modify the functions mentioned.

**Comment by SDeVuyst** [comment]
Hi! Apologies for this, but I do not need this feature anymore. Customer changed their mind :). Thanks anyways! Cheers
