### ISSUE TITLE
URL patterns loading issue

### ISSUE THREAD

**Issue by Pqpercut** [adamspd/django-appointment#181]
**Describe the bug**
Followed installation steps as specified in the docs quick start guide. Upon running server, seems to be an issue with loading the appointment URL. Despite exactly matching url, opens django debug page:

```
Request Method: | GET
http://127.0.0.1:8000/appointment/

Django tried these URL patterns, in this order:

appointment/ request/<int:service_id>/ [name='appointment_request']
appointment/ request-submit/ [name='appointment_request_submit']
appointment/ appointment/<str:id_request>/reschedule/ [name='prepare_reschedule_appointment']
appointment/ appointment-reschedule-submit/ [name='reschedule_appointment_submit']
appointment/ confirm-reschedule/<str:id_request>/ [name='confirm_reschedule']
appointment/ client-info/<int:appointment_request_id>/<str:id_request>/ [name='appointment_client_information']
appointment/ verification-code/<int:appointment_request_id>/<str:id_request>/ [name='enter_verification_code']
appointment/ verification-code/ [name='email_change_verification_code']
appointment/ thank-you/<int:appointment_id>/ [name='default_thank_you']
appointment/ verify/<uidb64>/<str:token>/ [name='set_passwd']
appointment/ ajax/
appointment/ app-admin/

The current path, appointment/, didn’t match any of these.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version  

**Smartphone (please complete the following information):**
 - Version 3.4.1

## Possible Solution
I am tired and there is absolutely the issue that I'm making a stupid error. Sorry if that's the case lmao.

## Can you fix the bug?
- [ ] Yes, I can fix the bug and will open a pull request.
- [x] No, I can't fix the bug, but I can assist in testing and providing feedback.
- [ ] No, I can't fix the bug, but I can provide more information to help you fix it.
- [ ] No, I can't fix the bug, but I can open an issue to report it.

**Comment by adamspd** [comment]
Hi @Pqpercut, sorry I missed your issue initially. The problem might stem from omitting `/appointment` in your URLs. However, based on your GET request, it appears that the URL you are trying to access does not exist in the project.

```
Request Method: | GET
http://127.0.0.1:8000/appointment/
```

Your issue resembles [this one](https://github.com/adamspd/django-appointment/issues/126#issuecomment-1981664283). Perhaps the solution there can assist you. If it does, please let me know and close the issue.

**Comment by Pqpercut** [comment]
Hi @adamspd,

Thanks, I was being really silly and it was just me messing up the urls. Thanks for your patience.

**Comment by adamspd** [comment]
Hi @Pqpercut, sometimes that happens to the best of us, don't worry about it. If you like the package, it would mean a lot to me if you give it a star.
