### ISSUE TITLE
Appointment lead-time, finish-time and slot-duration

### ISSUE THREAD

**Issue by pdelporte** [adamspd/django-appointment#2]
Thanks for this nice app.
This is more a request for an enhancement.
Would it be possible to define the lead-time, finish-time and slot-duration per service.
It would be also nice to a have a minimum time between two slot.
So if we define a service with a slot duration of 2h, a lead-time at 9 o'clock and an interval time of 30 minutes, the first slot would be 9h, the next one 11h30, then 14h, and so on.

**Comment by adamspd** [comment]
Hi, I will fix the #3 and then this one...
