### ISSUE TITLE
Error at AppointmentForm class

### ISSUE THREAD

**Issue by trid2q** [adamspd/django-appointment#226]
class AppointmentForm(forms.ModelForm):
  File &quot;/usr/local/lib/python3.10/site-packages/appointment/forms.py&quot;, line 43, in AppointmentForm
    phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial=&apos;US&apos;))
TypeError: MultiWidget.__init__() got an unexpected keyword argument &apos;initial&apos;

Version 3.6.0

Just change line 43 in forms.py FROM:

 phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(initial='US'))

TO:

    phone = PhoneNumberField(widget=PhoneNumberPrefixWidget({'initial':'US'}))

**Comment by adamspd** [comment]
Hi @trid2q there's a similar issue about this error. Are you using the same version of PhoneNumber as stated in requirements.txt ?

**Comment by trid2q** [comment]
This issue caused by different version of django-phonenumber-field.  When installing django-appointment 3.6.0, it automatically installs django-phonenumber-field 8.0.0 which causes issue.  Django-phonenumber-field 7.3.0 specified in requirements.txt resolves it.  So, I think we should either make django-appointment 3.6 install the right version or modify the code to use the update version of django-phonenumber-field.  Thanks.

**Comment by adamspd** [comment]
I have identified that the issue originates from [this line](https://github.com/adamspd/django-appointment/blob/main/setup.cfg#L28) in the `setup.cfg` file. The use of `>=` causes the latest version to be downloaded, which is not desirable for our requirements.
