### ISSUE TITLE
Model Naming 

### ISSUE THREAD

**Issue by Abhimanue-rajesh** [adamspd/django-appointment#281]
**Describe the bug**
Naming error, Can add verbose_name and verbose_name_plural

**To Reproduce**
1. Go to the admin panel
2. See error

**Expected behavior**
Should be Plural like Working Hours

**Screenshots**
![image](https://github.com/user-attachments/assets/555a4c4b-02a7-423d-a13c-6dbe466d3913)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.4
 - Browser : Firefox

## Possible Solution
Adding the verbose name

## Can you fix the bug?
- [ yes] Yes, I can fix the bug and will open a pull request.
- [ ] No, I can't fix the bug, but I can assist in testing and providing feedback.
- [ ] No, I can't fix the bug, but I can provide more information to help you fix it.
- [ ] No, I can't fix the bug, but I can open an issue to report it.

**Comment by adamspd** [comment]
Hi @Abhimanue-rajesh, thanks for noticing. I will wait for that pull request.
