### ISSUE TITLE
Broke the Demo Website

### ISSUE THREAD

**Issue by gasci** [adamspd/django-appointment#293]
Hi guys, I was playing with the demo app and I accidentally broke the database by removing a few users from the staff list.
https://django-appt.adamspierredavid.com/appointment/app-admin/appointments/

I would suggest you to reset the database.

**Comment by adamspd** [comment]
No worries, it resets every 2 hours by itself...

**Comment by gasci** [comment]
Thank you for the information.

**Comment by gasci** [comment]
Great project btw!

**Comment by adamspd** [comment]
> Great project btw!

Thank you 🙏 I haven't had more time to refine it, and add more features. Feel free to do a pull request if anything comes to mind.
