### ISSUE TITLE
Booking the first appointment of the day makes all the others unavailable

### ISSUE THREAD

**Issue by pdelporte** [adamspd/django-appointment#3]
Hello,
Let's configure the settings like those:
APPOINTMENT_SLOT_DURATION = 120  # minutes
APPOINTMENT_LEAD_TIME = (11, 0)  # (hour, minute) 24-hour format
APPOINTMENT_FINISH_TIME = (14, 0)  # (hour, minute) 24-hour format

A service with a duration of 2 hours.

When you want to book a slot you see well the two slots : 11am and 1pm
If I book the slot at 1pm, I can also book the slot of 11am
But if I first book the slot of 11am, then when I come back to book again the slot of 1pm, it just says No availability.
Checking the appointment, I have only one for the specified date

**Comment by adamspd** [comment]
Hi, I will try and reproduce this to fix it as soon as possible.

**Comment by adamspd** [comment]
Hello @pdelporte, 
  
Thank you for bringing this issue to my attention. I appreciated your detailed description of the problem, and I'm glad to inform you that I've implemented a fix for it.

I've also added comprehensive tests to ensure that the specific situation you described is handled correctly in the future. This will help me maintain the integrity and reliability of the code.

Please update to the latest version and test it out on your end. If you encounter any further issues or have any questions, please don't hesitate to reach out. Your feedback is invaluable to me, and I'm here to assist you.

Thank you once again for your contribution to improving the package.
