### ISSUE TITLE
Mixing slot reservations between services

### ISSUE THREAD

**Issue by pdelporte** [adamspd/django-appointment#4]
If you have two services defined, if you make a reservation for one service, in this case the first one, no time slot are available for the second one. It seems to only take into account the first service or first reservation that it found. The information showed of the service is well the right one.

**Comment by adamspd** [comment]
Hi @pdelporte,

Thank you for highlighting this aspect of the functionality. Originally, the design was based on the assumption that all services were provided by a single individual, which naturally required that person to be available even if the services were different.

The feedback in issue #1 has led us to recognize the need for a more flexible approach. With the addition of staff functionalities and the ability to cater to diverse services and schedules, I am working to address this limitation.

I appreciate your insight into this matter, and I assure you that the upcoming enhancements will provide a solution that aligns with the diverse needs of service providers.

Please don't hesitate to reach out if you have any further questions or concerns.

Best Regards,
@adamspd
